metadata:
  creationTimestamp: "2024-06-27T11:37:52Z"
  generation: 130
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:destination:
          .: {}
          f:namespace: {}
          f:server: {}
        f:project: {}
        f:source:
          .: {}
          f:path: {}
          f:repoURL: {}
        f:syncPolicy:
          .: {}
          f:automated: {}
      f:status:
        .: {}
        f:health: {}
        f:summary: {}
        f:sync:
          .: {}
          f:comparedTo:
            .: {}
            f:destination: {}
            f:source: {}
    manager: argocd-server
    operation: Update
    time: "2024-06-27T13:15:58Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:controllerNamespace: {}
        f:health:
          f:status: {}
        f:history: {}
        f:operationState:
          .: {}
          f:finishedAt: {}
          f:message: {}
          f:operation:
            .: {}
            f:initiatedBy:
              .: {}
              f:automated: {}
            f:retry:
              .: {}
              f:limit: {}
            f:sync:
              .: {}
              f:revision: {}
          f:phase: {}
          f:startedAt: {}
          f:syncResult:
            .: {}
            f:resources: {}
            f:revision: {}
            f:source:
              .: {}
              f:path: {}
              f:repoURL: {}
        f:reconciledAt: {}
        f:resources: {}
        f:sourceType: {}
        f:summary:
          f:externalURLs: {}
          f:images: {}
        f:sync:
          f:comparedTo:
            f:destination:
              f:namespace: {}
              f:server: {}
            f:source:
              f:path: {}
              f:repoURL: {}
          f:revision: {}
          f:status: {}
    manager: argocd-application-controller
    operation: Update
    time: "2024-06-27T13:17:40Z"
  name: demo-service
  namespace: argocd
  resourceVersion: "15034"
  uid: d960d709-2d4d-47e4-82f3-abd144fefea0
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demoargo
    repoURL: https://github.com/little-bear-creator/DemoManifests.git
  syncPolicy:
    automated: {}
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-06-27T11:38:14Z"
    deployedAt: "2024-06-27T11:38:14Z"
    id: 0
    initiatedBy:
      username: admin
    revision: 305598d9392a2460e2540ebb114d2157b50f417d
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T11:50:12Z"
    deployedAt: "2024-06-27T11:50:12Z"
    id: 1
    initiatedBy:
      username: admin
    revision: 0af725b43b6a3777a7ba8f11647e9ad6d896009a
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T11:56:48Z"
    deployedAt: "2024-06-27T11:56:48Z"
    id: 2
    initiatedBy:
      username: admin
    revision: 906782b8f2c2915d071717390b51f2382f92929e
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T12:08:53Z"
    deployedAt: "2024-06-27T12:08:53Z"
    id: 3
    initiatedBy:
      username: admin
    revision: 8b6ee8ccb98012dc9add98e2a57290fad6e89c10
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T12:12:43Z"
    deployedAt: "2024-06-27T12:12:43Z"
    id: 4
    initiatedBy:
      username: admin
    revision: 32d686163d80525e965ee526de7d86dfe4a7f5b2
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T12:35:31Z"
    deployedAt: "2024-06-27T12:35:31Z"
    id: 5
    initiatedBy:
      automated: true
    revision: 2611df3da8b929c1610f4475bc09bb4412aa7627
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T12:59:28Z"
    deployedAt: "2024-06-27T12:59:28Z"
    id: 6
    initiatedBy:
      automated: true
    revision: efa5fa55d05338be2d9b10de32255232eed86f4e
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T12:59:42Z"
    deployedAt: "2024-06-27T12:59:42Z"
    id: 7
    initiatedBy:
      username: admin
    revision: efa5fa55d05338be2d9b10de32255232eed86f4e
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T13:07:17Z"
    deployedAt: "2024-06-27T13:07:17Z"
    id: 8
    initiatedBy:
      username: admin
    revision: efa5fa55d05338be2d9b10de32255232eed86f4e
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  - deployStartedAt: "2024-06-27T13:17:37Z"
    deployedAt: "2024-06-27T13:17:37Z"
    id: 9
    initiatedBy:
      automated: true
    revision: 3d268f63e89d7b88b8fca1297248771c6b744390
    source:
      path: demoargo
      repoURL: https://github.com/little-bear-creator/DemoManifests.git
  operationState:
    finishedAt: "2024-06-27T13:17:37Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 3d268f63e89d7b88b8fca1297248771c6b744390
    phase: Succeeded
    startedAt: "2024-06-27T13:17:37Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/demo-service unchanged
        name: demo-service
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/demo-deployment configured
        name: demo-deployment
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/minimal-ingress unchanged
        name: minimal-ingress
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 3d268f63e89d7b88b8fca1297248771c6b744390
      source:
        path: demoargo
        repoURL: https://github.com/little-bear-creator/DemoManifests.git
  reconciledAt: "2024-06-27T13:17:37Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: demo-service
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: demo-deployment
    namespace: default
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: minimal-ingress
    namespace: default
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://mondomaine.local/
    images:
    - 989988/demoapp:1.0.0
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: demoargo
        repoURL: https://github.com/little-bear-creator/DemoManifests.git
    revision: 3d268f63e89d7b88b8fca1297248771c6b744390
    status: Synced
